server:
  port: 8080

spring:
  #config:
    #import: optional:configserver:http://localhost:8761
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-cliente
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/client/**
        - id: msvc-pedido
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/pedido/**
    config:
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: false