server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: msvc-pedido
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    #config:
    # import: optional:configserver:http://localhost:8888
  cloud:
    config:
      import-check:
        enabled: false


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka